/* Auto-generated by gen_config.py — do not edit */
#ifndef BOARD_H
#define BOARD_H

#include <stdbool.h>
#include <stdint.h>

/* --- GPIO pins --- */
#include "driverlib/gpio.h"
#include "inc/hw_memmap.h"
#define GPIO_BT_RX_PORT   GPIO_PORTA_BASE
#define GPIO_BT_RX_PIN    GPIO_PIN_0
#define GPIO_BT_RX_MASK   GPIO_PIN_0
#define GPIO_BT_TX_PORT   GPIO_PORTA_BASE
#define GPIO_BT_TX_PIN    GPIO_PIN_1
#define GPIO_BT_TX_MASK   GPIO_PIN_1
#define GPIO_DBG_RX_PORT   GPIO_PORTE_BASE
#define GPIO_DBG_RX_PIN    GPIO_PIN_0
#define GPIO_DBG_RX_MASK   GPIO_PIN_0
#define GPIO_DBG_TX_PORT   GPIO_PORTE_BASE
#define GPIO_DBG_TX_PIN    GPIO_PIN_1
#define GPIO_DBG_TX_MASK   GPIO_PIN_1
#define GPIO_I2C_SCL_PORT   GPIO_PORTB_BASE
#define GPIO_I2C_SCL_PIN    GPIO_PIN_2
#define GPIO_I2C_SCL_MASK   GPIO_PIN_2
#define GPIO_I2C_SDA_PORT   GPIO_PORTB_BASE
#define GPIO_I2C_SDA_PIN    GPIO_PIN_3
#define GPIO_I2C_SDA_MASK   GPIO_PIN_3
#define GPIO_RGB_LED_PORT   GPIO_PORTC_BASE
#define GPIO_RGB_LED_PIN    GPIO_PIN_3
#define GPIO_RGB_LED_MASK   GPIO_PIN_3
#define GPIO_SSI_CLK_PORT   GPIO_PORTA_BASE
#define GPIO_SSI_CLK_PIN    GPIO_PIN_2
#define GPIO_SSI_CLK_MASK   GPIO_PIN_2
#define GPIO_LCD_CS_PORT   GPIO_PORTA_BASE
#define GPIO_LCD_CS_PIN    GPIO_PIN_3
#define GPIO_LCD_CS_MASK   GPIO_PIN_3
#define GPIO_SSI_RX_PORT   GPIO_PORTA_BASE
#define GPIO_SSI_RX_PIN    GPIO_PIN_4
#define GPIO_SSI_RX_MASK   GPIO_PIN_4
#define GPIO_SSI_TX_PORT   GPIO_PORTA_BASE
#define GPIO_SSI_TX_PIN    GPIO_PIN_5
#define GPIO_SSI_TX_MASK   GPIO_PIN_5
#define GPIO_LCD_RST_PORT   GPIO_PORTF_BASE
#define GPIO_LCD_RST_PIN    GPIO_PIN_0
#define GPIO_LCD_RST_MASK   GPIO_PIN_0
#define GPIO_LCD_DC_PORT   GPIO_PORTF_BASE
#define GPIO_LCD_DC_PIN    GPIO_PIN_1
#define GPIO_LCD_DC_MASK   GPIO_PIN_1
#define GPIO_LCD_BL_PORT   GPIO_PORTF_BASE
#define GPIO_LCD_BL_PIN    GPIO_PIN_2
#define GPIO_LCD_BL_MASK   GPIO_PIN_2
#define GPIO_NRF_CS_PORT   GPIO_PORTA_BASE
#define GPIO_NRF_CS_PIN    GPIO_PIN_6
#define GPIO_NRF_CS_MASK   GPIO_PIN_6
#define GPIO_NRF_CE_PORT   GPIO_PORTB_BASE
#define GPIO_NRF_CE_PIN    GPIO_PIN_0
#define GPIO_NRF_CE_MASK   GPIO_PIN_0
#define GPIO_NRF_IRQ_PORT   GPIO_PORTB_BASE
#define GPIO_NRF_IRQ_PIN    GPIO_PIN_1
#define GPIO_NRF_IRQ_MASK   GPIO_PIN_1
#define GPIO_JS1_BTN_PORT   GPIO_PORTC_BASE
#define GPIO_JS1_BTN_PIN    GPIO_PIN_4
#define GPIO_JS1_BTN_MASK   GPIO_PIN_4
#define GPIO_JS2_BTN_PORT   GPIO_PORTB_BASE
#define GPIO_JS2_BTN_PIN    GPIO_PIN_6
#define GPIO_JS2_BTN_MASK   GPIO_PIN_6
#define GPIO_BAT_ADC_PORT   GPIO_PORTE_BASE
#define GPIO_BAT_ADC_PIN    GPIO_PIN_3
#define GPIO_BAT_ADC_MASK   GPIO_PIN_3

/* --- Peripheral bindings --- */
#include "bsp_uart.h"
#include "bsp_i2c.h"
#include "bsp_adc.h"
#include "bsp_spi.h"
#define BOARD_SYSCLK_HZ  80000000
extern const bsp_uart_config_t BOARD_UART_BT_CFG;
extern const bsp_uart_config_t BOARD_UART_DEBUG_CFG;
extern const bsp_i2c_config_t BOARD_I2C_CFG;
extern const bsp_adc_config_t BOARD_BATTERY_ADC_CFG;
extern const bsp_adc_config_t BOARD_JOY_ADC_CFG;
extern const bsp_spi_config_t BOARD_SPI_CFG;

/* --- Board --- */
bool Board_UartDebug_Init(void);
bool Board_Periph_Init(void);
void UART_Putc(char c);
void UART_Puts(const char* s);
int UART_Getc(char *c);
void UART_Flush(void);
void UART_Debug_Putc(char c);
void UART_Debug_Puts(const char* s);
int UART_Debug_Getc(char *c);

#endif