/* Auto-generated by gen_config.py — do not edit */
#ifndef BOARD_H
#define BOARD_H

#include <stdbool.h>
#include <stdint.h>

/* --- GPIO pins --- */
#include "driverlib/gpio.h"
#include "inc/hw_memmap.h"
#define GPIO_M1_IN1_PORT   GPIO_PORTF_BASE
#define GPIO_M1_IN1_PIN    GPIO_PIN_4
#define GPIO_M1_IN1_MASK   GPIO_PIN_4
#define GPIO_M1_IN2_PORT   GPIO_PORTC_BASE
#define GPIO_M1_IN2_PIN    GPIO_PIN_7
#define GPIO_M1_IN2_MASK   GPIO_PIN_7
#define GPIO_M2_IN1_PORT   GPIO_PORTC_BASE
#define GPIO_M2_IN1_PIN    GPIO_PIN_4
#define GPIO_M2_IN1_MASK   GPIO_PIN_4
#define GPIO_M2_IN2_PORT   GPIO_PORTA_BASE
#define GPIO_M2_IN2_PIN    GPIO_PIN_6
#define GPIO_M2_IN2_MASK   GPIO_PIN_6
#define GPIO_M3_IN1_PORT   GPIO_PORTA_BASE
#define GPIO_M3_IN1_PIN    GPIO_PIN_7
#define GPIO_M3_IN1_MASK   GPIO_PIN_7
#define GPIO_M3_IN2_PORT   GPIO_PORTF_BASE
#define GPIO_M3_IN2_PIN    GPIO_PIN_0
#define GPIO_M3_IN2_MASK   GPIO_PIN_0
#define GPIO_M4_IN1_PORT   GPIO_PORTF_BASE
#define GPIO_M4_IN1_PIN    GPIO_PIN_1
#define GPIO_M4_IN1_MASK   GPIO_PIN_1
#define GPIO_M4_IN2_PORT   GPIO_PORTF_BASE
#define GPIO_M4_IN2_PIN    GPIO_PIN_2
#define GPIO_M4_IN2_MASK   GPIO_PIN_2
#define GPIO_M1_PWM_PORT   GPIO_PORTB_BASE
#define GPIO_M1_PWM_PIN    GPIO_PIN_6
#define GPIO_M1_PWM_MASK   GPIO_PIN_6
#define GPIO_M2_PWM_PORT   GPIO_PORTB_BASE
#define GPIO_M2_PWM_PIN    GPIO_PIN_7
#define GPIO_M2_PWM_MASK   GPIO_PIN_7
#define GPIO_M3_PWM_PORT   GPIO_PORTB_BASE
#define GPIO_M3_PWM_PIN    GPIO_PIN_4
#define GPIO_M3_PWM_MASK   GPIO_PIN_4
#define GPIO_M4_PWM_PORT   GPIO_PORTB_BASE
#define GPIO_M4_PWM_PIN    GPIO_PIN_5
#define GPIO_M4_PWM_MASK   GPIO_PIN_5
#define GPIO_M1_ENCA_PORT   GPIO_PORTC_BASE
#define GPIO_M1_ENCA_PIN    GPIO_PIN_5
#define GPIO_M1_ENCA_MASK   GPIO_PIN_5
#define GPIO_M1_ENCB_PORT   GPIO_PORTC_BASE
#define GPIO_M1_ENCB_PIN    GPIO_PIN_6
#define GPIO_M1_ENCB_MASK   GPIO_PIN_6
#define GPIO_M2_ENCA_PORT   GPIO_PORTD_BASE
#define GPIO_M2_ENCA_PIN    GPIO_PIN_6
#define GPIO_M2_ENCA_MASK   GPIO_PIN_6
#define GPIO_M2_ENCB_PORT   GPIO_PORTD_BASE
#define GPIO_M2_ENCB_PIN    GPIO_PIN_7
#define GPIO_M2_ENCB_MASK   GPIO_PIN_7
#define GPIO_M3_ENCA_PORT   GPIO_PORTF_BASE
#define GPIO_M3_ENCA_PIN    GPIO_PIN_3
#define GPIO_M3_ENCA_MASK   GPIO_PIN_3
#define GPIO_M3_ENCB_PORT   GPIO_PORTD_BASE
#define GPIO_M3_ENCB_PIN    GPIO_PIN_4
#define GPIO_M3_ENCB_MASK   GPIO_PIN_4
#define GPIO_M4_ENCA_PORT   GPIO_PORTD_BASE
#define GPIO_M4_ENCA_PIN    GPIO_PIN_5
#define GPIO_M4_ENCA_MASK   GPIO_PIN_5
#define GPIO_M4_ENCB_PORT   GPIO_PORTB_BASE
#define GPIO_M4_ENCB_PIN    GPIO_PIN_0
#define GPIO_M4_ENCB_MASK   GPIO_PIN_0
#define GPIO_BAT_ADC_PORT   GPIO_PORTE_BASE
#define GPIO_BAT_ADC_PIN    GPIO_PIN_3
#define GPIO_BAT_ADC_MASK   GPIO_PIN_3
#define GPIO_BTN_ADC_PORT   GPIO_PORTE_BASE
#define GPIO_BTN_ADC_PIN    GPIO_PIN_2
#define GPIO_BTN_ADC_MASK   GPIO_PIN_2
#define GPIO_LINE1_PORT   GPIO_PORTD_BASE
#define GPIO_LINE1_PIN    GPIO_PIN_3
#define GPIO_LINE1_MASK   GPIO_PIN_3
#define GPIO_LINE2_PORT   GPIO_PORTD_BASE
#define GPIO_LINE2_PIN    GPIO_PIN_2
#define GPIO_LINE2_MASK   GPIO_PIN_2
#define GPIO_LINE3_PORT   GPIO_PORTD_BASE
#define GPIO_LINE3_PIN    GPIO_PIN_1
#define GPIO_LINE3_MASK   GPIO_PIN_1
#define GPIO_LINE4_PORT   GPIO_PORTD_BASE
#define GPIO_LINE4_PIN    GPIO_PIN_0
#define GPIO_LINE4_MASK   GPIO_PIN_0
#define GPIO_LINE5_PORT   GPIO_PORTE_BASE
#define GPIO_LINE5_PIN    GPIO_PIN_5
#define GPIO_LINE5_MASK   GPIO_PIN_5
#define GPIO_LINE6_PORT   GPIO_PORTE_BASE
#define GPIO_LINE6_PIN    GPIO_PIN_4
#define GPIO_LINE6_MASK   GPIO_PIN_4
#define GPIO_BUZZER_PORT   GPIO_PORTB_BASE
#define GPIO_BUZZER_PIN    GPIO_PIN_1
#define GPIO_BUZZER_MASK   GPIO_PIN_1
#define GPIO_RGB_LED_PORT   GPIO_PORTC_BASE
#define GPIO_RGB_LED_PIN    GPIO_PIN_3
#define GPIO_RGB_LED_MASK   GPIO_PIN_3
#define GPIO_ULTRA_TRIG_PORT   GPIO_PORTC_BASE
#define GPIO_ULTRA_TRIG_PIN    GPIO_PIN_2
#define GPIO_ULTRA_TRIG_MASK   GPIO_PIN_2
#define GPIO_ULTRA_ECHO_PORT   GPIO_PORTC_BASE
#define GPIO_ULTRA_ECHO_PIN    GPIO_PIN_1
#define GPIO_ULTRA_ECHO_MASK   GPIO_PIN_1
#define GPIO_BT_RX_PORT   GPIO_PORTA_BASE
#define GPIO_BT_RX_PIN    GPIO_PIN_0
#define GPIO_BT_RX_MASK   GPIO_PIN_0
#define GPIO_BT_TX_PORT   GPIO_PORTA_BASE
#define GPIO_BT_TX_PIN    GPIO_PIN_1
#define GPIO_BT_TX_MASK   GPIO_PIN_1
#define GPIO_I2C_SCL_PORT   GPIO_PORTB_BASE
#define GPIO_I2C_SCL_PIN    GPIO_PIN_2
#define GPIO_I2C_SCL_MASK   GPIO_PIN_2
#define GPIO_I2C_SDA_PORT   GPIO_PORTB_BASE
#define GPIO_I2C_SDA_PIN    GPIO_PIN_3
#define GPIO_I2C_SDA_MASK   GPIO_PIN_3
#define GPIO_DBG_RX_PORT   GPIO_PORTE_BASE
#define GPIO_DBG_RX_PIN    GPIO_PIN_0
#define GPIO_DBG_RX_MASK   GPIO_PIN_0
#define GPIO_DBG_TX_PORT   GPIO_PORTE_BASE
#define GPIO_DBG_TX_PIN    GPIO_PIN_1
#define GPIO_DBG_TX_MASK   GPIO_PIN_1
#define GPIO_SSI_CLK_PORT   GPIO_PORTA_BASE
#define GPIO_SSI_CLK_PIN    GPIO_PIN_2
#define GPIO_SSI_CLK_MASK   GPIO_PIN_2
#define GPIO_SSI_FSS_PORT   GPIO_PORTA_BASE
#define GPIO_SSI_FSS_PIN    GPIO_PIN_3
#define GPIO_SSI_FSS_MASK   GPIO_PIN_3
#define GPIO_SSI_RX_PORT   GPIO_PORTA_BASE
#define GPIO_SSI_RX_PIN    GPIO_PIN_4
#define GPIO_SSI_RX_MASK   GPIO_PIN_4
#define GPIO_SSI_TX_PORT   GPIO_PORTA_BASE
#define GPIO_SSI_TX_PIN    GPIO_PIN_5
#define GPIO_SSI_TX_MASK   GPIO_PIN_5

/* --- Peripheral bindings --- */
#include "bsp_uart.h"
#include "bsp_i2c.h"
#include "bsp_adc.h"
#include "bsp_timer.h"
#include "bsp_qei.h"
#include "bsp_spi.h"
#define BOARD_SYSCLK_HZ  80000000
extern const bsp_pwm_config_t BOARD_PWM_CFG;
extern const bsp_qei_config_t BOARD_QEI_CFG;
extern const bsp_uart_config_t BOARD_UART_BT_CFG;
extern const bsp_uart_config_t BOARD_UART_DEBUG_CFG;
extern const bsp_i2c_config_t BOARD_I2C_CFG;
extern const bsp_adc_config_t BOARD_LINE_ADC_CFG;
extern const bsp_adc_config_t BOARD_BATTERY_ADC_CFG;
extern const bsp_spi_config_t BOARD_SPI_CFG;

/* --- Motor --- */
#define SYSCLK_HZ    80000000
#define PWM_FREQ_HZ  10000
#define PWM_PERIOD   (SYSCLK_HZ / PWM_FREQ_HZ)
#define MOTOR_RPM_FULL_SCALE 300
#define MOTOR_MIN_DUTY 120U
#define BOARD_MOTOR_COUNT 4U
#define M1_TIMER  TIMER0_BASE
#define M1_PWM_CH TIMER_A
#define M2_TIMER  TIMER0_BASE
#define M2_PWM_CH TIMER_B
#define M3_TIMER  TIMER1_BASE
#define M3_PWM_CH TIMER_A
#define M4_TIMER  TIMER1_BASE
#define M4_PWM_CH TIMER_B
void Motor_Init(void);
void Motor_SetOutput(uint8_t motor_id, int32_t rpm, uint16_t duty_permille);
void Motor_SetSpeed(uint8_t motor_id, int32_t rpm);

/* --- Encoder --- */
#define BOARD_ENCODER_COUNT 4U
void Encoder_Init(void);
int32_t Encoder_GetCount(uint8_t index);
void Encoder_ResetCount(uint8_t index);

/* --- Line --- */
#define LINE_SENSOR_COUNT 6U
bool Line_IsReady(void);
bool Line_Sample(uint16_t *out, size_t count);
void Line_Init(void);

/* --- Board --- */
bool Board_UartDebug_Init(void);
bool Board_Periph_Init(void);
bool Board_Ultra_Init(void);
void UART_Putc(char c);
void UART_Puts(const char* s);
int UART_Getc(char *c);
void UART_Flush(void);
void UART_Debug_Putc(char c);
void UART_Debug_Puts(const char* s);
int UART_Debug_Getc(char *c);

#endif