/* Auto-generated by gen_config.py — do not edit */
#ifndef MODULE_BOARD_H
#define MODULE_BOARD_H
bool Board_UartDebug_Init(void);
bool Board_Periph_Init(void);
void UART_Putc(char c);
void UART_Puts(const char* s);
int UART_Getc(char *c);
void UART_Debug_Putc(char c);
void UART_Debug_Puts(const char* s);
int UART_Debug_Getc(char *c);
#endif