/* Auto-generated by gen_config.py — do not edit */
#ifndef MODULE_ENCODER_H
#define MODULE_ENCODER_H
#include <stdint.h>
void Encoder_Init(void);
int32_t Encoder_GetCount(uint8_t index);
#endif