/* Auto-generated by gen_config.py — do not edit */
#ifndef MODULE_MOTOR_H
#define MODULE_MOTOR_H
#include <stdint.h>
#define SYSCLK_HZ    80000000
#define PWM_FREQ_HZ  10000
#define PWM_PERIOD   (SYSCLK_HZ / PWM_FREQ_HZ)

#define M1_TIMER  TIMER0_BASE
#define M1_PWM_CH TIMER_A
#define M2_TIMER  TIMER0_BASE
#define M2_PWM_CH TIMER_B
#define M3_TIMER  TIMER1_BASE
#define M3_PWM_CH TIMER_A
#define M4_TIMER  TIMER1_BASE
#define M4_PWM_CH TIMER_B

void Motor_Init(void);
void Motor_SetSpeed(uint8_t motor_id, int32_t rpm);
#endif