/* Auto-generated by gen_config.py — do not edit */
#ifndef PERIPH_BIND_H
#define PERIPH_BIND_H

#include "bsp_uart.h"
#include "bsp_i2c.h"
#include "bsp_adc.h"
#include "bsp_timer.h"
#include "bsp_qei.h"
#include "bsp_spi.h"

#define BOARD_SYSCLK_HZ  80000000

extern const bsp_pwm_config_t BOARD_PWM_CFG;
extern const bsp_qei_config_t BOARD_QEI_CFG;
extern const bsp_uart_config_t BOARD_UART_BT_CFG;
extern const bsp_uart_config_t BOARD_UART_DEBUG_CFG;
extern const bsp_i2c_config_t BOARD_I2C_CFG;
extern const bsp_adc_config_t BOARD_ADC_CFG;
extern const bsp_adc_config_t BOARD_BATTERY_ADC_CFG;
extern const bsp_spi_config_t BOARD_SPI_CFG;

#endif